# Generated by Django 4.2.7 on 2024-02-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='media/project/images/')),
                ('video', models.FileField(upload_to='media/project/video')),
                ('live_link', models.URLField(max_length=256)),
            ],
        ),
    ]
